== Geopaparazzi Tables


=== Geopaparazzi Project Database Tables

The Geopaparazzi Project Database is a plain SQLite v3 database with the extension **.gpap**.  It contains all the data collected during a Geopaparazzi session, such as GPS logs, notes (including images), and bookmarks.

All coordinate data are saved in http://gisgeography.com/wgs84-world-geodetic-system/[WGS84] horizontal spatial reference system.  The elevation data saved by Geopaparazzi is as reported by the GPS for the device and is likely the height relative to the WGS84 ellipsoid and not a vertical datum or some other spatially varying surface like Mean Sea Level.

.Overview diagram of database tables
[plantuml, 10_database/database_diagram, png]     
....
class metadata << (T,#5d9d76) Table >>{
    key: TEXT NOT NULL
    label: TEXT
    value: TEXT NOT NULL
}
class notes << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    lon: REAL NOT NULL
    lat: REAL NOT NULL
    altim: REAL NOT NULL
    ts: DATE NOT NULL
    description: TEXT
    text: TEXT NOT NULL
    form: CLOB
    style: TEXT
    isdirty: INTEGER
}
class images << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    lon: REAL NOT NULL
    lat: REAL NOT NULL
    altim: REAL NOT NULL
    azim: REAL NOT NULL
    imagedata_id: INTEGER NOT NULL
    ts: DATE NOT NULL
    text: TEXT NOT NULL
    note_id: INTEGER
    isdirty: INTEGER NOT NULL
}
class imagedata << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    data: BLOB NOT NULL
    thumbnail: BLOB NOT NULL
}
class gpslogs << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    startts: LONG NOT NULL
    endts: LONG NOT NULL
    lengthm: REAL NOT NULL
    isdirty: INTEGER NOT NULL
    text: TEXT NOT NULL
}
class gpslogsdata << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    lon: REAL NOT NULL
    lat: REAL NOT NULL
    altim: REAL NOT NULL
    ts: DATE NOT NULL
    logid: INTEGER NOT NULL
}
class gpslogsproperties << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    logid: INTEGER NOT NULL
    color: TEXT NOT NULL
    width: REAL NOT NULL
    visible: INTEGER NOT NULL
}
class bookmarks << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    lon: REAL NOT NULL
    lat: REAL NOT NULL
    zoom: REAL NOT NULL
    bnorth: REAL NOT NULL
    bsouth: REAL NOT NULL
    bwest: REAL NOT NULL
    beast: REAL NOT NULL
    text: TEXT NOT NULL
}
class log << (T,#5d9d76) Table >>{
    _id: INTEGER PRIMARY KEY
    dataora: INTEGER NOT NULL
    logmsg: TEXT
}

gpslogs <-- gpslogsdata
gpslogs <-- gpslogsproperties
images <-- imagedata
notes <-- images
....


====  Using Geopaparazzi Timestamps

Geopaparazzi stores timestamps (e.g. columns named "ts" in the tables below) as long integers and represent https://en.wikipedia.org/wiki/Unix_time[Unix Epoch], but instead of seconds the value is in milliseconds.

To make the values more readable, they can be decoded in SQLite like so (note the dividing by 1000 to change the milliseconds into seconds):

----------------------------------------------
  SELECT _id, ts, datetime("ts"/1000, "unixepoch") timestamp FROM notes;
----------------------------------------------

results in:

[width="75%",cols="2,6,10",options=""header]
|====================
| _id |       ts      |    timestamp
|  1  | 1419293026593 | 2014-12-23 00:03:46 
|====================

Typically the values must be decoded into a standard format like https://en.wikipedia.org/wiki/ISO_8601[ISO 8601] to be used in other applications.  The values can be decoded in SQLite like so (note the dividing by 1000 to change the milliseconds into seconds):

----------------------------------------------
SELECT ROWID, ts, strftime( '%Y-%m-%dT%H:%M:%SZ',datetime("ts"/1000, 'unixepoch')) timestamp FROM notes;
----------------------------------------------

results in:

[width="75%",cols="2,6,10",options=""header]
|====================
| _id |       ts      |    timestamp
|  1  | 1419293026593 | 2014-12-23T00:03:46Z
|====================

You can also create https://www.w3resource.com/sqlite/sqlite-create-drop-views.php[SQL Views] to persist the above query in the database.

----------------------------------------------
CREATE VIEW v_notes AS 
  SELECT *, strftime( '%Y-%m-%dT%H:%M:%SZ',datetime("ts"/1000, 'unixepoch')) timestamp FROM notes;
  
SELECT * FROM v_notes;
----------------------------------------------


==== Geopaparazzi Table Descriptions

.The metadata Table
[width="100%",cols="2,10"]
|====================
| key   | key for the record  
| label | text for dialog label
| value | value for the record
|====================
This table holds 7 standard rows of the various Project information such as the Project name.  You can add your own metadata rows using the Project Info dialog in Geopaparazzi or using SQL.

.The notes Table
[width="100%",cols="2,10"]
|====
| _id           | unique id                            
|lon            | longitude of the note, decimal degrees
|lat            | latitude of the note, decimal degrees
|altim          | elevation, meters 
|ts             | timestamp, "unixepoch" in milliseconds
|description    | description of the note 
|text           | text/type of the note 
|form           | the form notes data, JSON
|isdirty        | is dirty field (0 = false, 1 = true) (not used)
|style          | style of the note (not used)
|====

NOTE: Style and isdirty are currently unused.

.The images Table
[width="100%",cols="2,10"]
|====
| _id            |unique id               
|lon             |longitude of the image, decimal degrees
|lat             |latitude of the image, decimal degrees
|altim           |elevation, meters 
|azim            |azimuth, decimal degrees
|imagedata_id    |foreign key to _id of the imagedata table
|ts              |timestamp, "unixepoch" in milliseconds
|text            |file name of the image
|note_id         |optional foreign key to _id of the notes table
|isdirty         |is dirty field (0 = false, 1 = true)
|====

.The imagedata Table
[width="100%",cols="2,10"]
|====
| _id            |unique id               
|data            |the image data as a BLOB containing an JPEG image
|thumbnail       |the image thumbnail data as a BLOB containing an JPEG image
|====


.The bookmarks Table
[width="100%",cols="2,10"]
|====
| _id      |unique id               
|lon      |longitude of the bookmark, decimal degrees
|lat      |latitude of the bookmark, decimal degrees
|zoom     |the zoom of the bookmark, https://wiki.openstreetmap.org/wiki/Zoom_levels[Tile zoom levels]

|north    |the north bound of the bookmark, decimal degrees
|south    |the south bound of the bookmark, decimal degrees
|west     |the west bound of the bookmark, decimal degrees
|east     |the east bound of the bookmark, decimal degrees
|text     |the name of the bookmark 
|====


.The gpslogs Table
[width="100%",cols="2,10"]
|====
| _id     | unique id               
|startts   |log start timestamp, "unixepoch" in milliseconds
|endts     |log end timestamp , "unixepoch" in milliseconds
|lengthm   |the length in meters
|isdirty   |is dirty field (0 = false, 1 = true)
|text      |name of the log
|====

.The gpslogsdata Table
[width="100%",cols="2,10"]
|====
| _id     |unique id               
|lon      |longitude of the log point, decimal degrees
|lat      |latitude of the log point, decimal degrees
|altim    |elevation of the log point, meters
|ts       |timestamp of the log point, "unixepoch" in milliseconds
|logid    |foreign key to _id of the gpslogs table 
|====

.The gpslogsproperties Table
[width="100%",cols="2,10"]
|====
| _id      |unique id               
|logid     |foreign key to _id of the gpslogs table 
|color     |the color to use to draw the log, text like "red", etc
|width     |the width to use to draw the log, in pixels
|visible   |flag that defines if the log is visible at the time given 
|====

.The log Table
[width="100%",cols="2,10"]
|====
| _id      |unique id               
|dataora   |row timestamp in milliseconds
|logmsg    |log message 
|====

The ``log`` table contains rows created by Geopaparazzi as you use its various functions, primarily for troubleshooting any problems.  You can view the log table in Geopaparazzi by selecting the menu in the main dashboard view and selecting Advanced, the select "Analyze log".  By default it shows the "Error" class messages.

=== Additional Geopaparazzi tables in Spatialite Databases
anchor:Spatialite_Databases[]

If these tables are present in a Spatialite database used as a map overlay, they can supply additional properties to the Spatialite data.

.The dataproperties Table
[width="100%",cols="2,10"]
|====
| _id            |unique id
|name            |source of the geometry, format: ``database_path#table#column``
|size            |
|fillcolor       |fill color in HTML-friendly form: e.g. red, #FBC02D, etc
|strokecolor     |outline color
|fillalpha       |0.0 to 1.0 value of opacity (0=fully transparent, 1=not transparent)
|strokealpha     |0.0 to 1.0 value of opacity (0=fully transparent, 1=not transparent)
|shape           |allowed values: "square","cross",triangle","circle","star","X"
|width           |width of line
|labelsize       |size of label in scaled pixels
|labelfield      |field in feature table to get label text
|labelvisible    |is the label shown? 0=no, 1=yes
|enabled         |
|layerorder      |
|dashpattern     |dashWidth, dashGap, dashWidth2, dashGap2, ... in scaled pixels, e.g. ``10,20``
|minzoom         |don't show if current zoom level is less than this (see  https://wiki.openstreetmap.org/wiki/Zoom_levels[Tile zoom levels] for values)
|maxzoom         |don't show if current zoom level is greater than this
|decimationfactor|
|theme           |
|====

The ``dataproperties`` table is useful for providing persistent styling of features stored in the Spatialite database.

An example of a "name" value in the ``dataproperties`` table:

----------------------------------------
/storage/emulated/0/rigstreet_v1.sqlite#sites_gate#geometry
----------------------------------------


.The geopap_resource Table
[width="100%",cols="2,10"]
|====
| id      |unique id
| restable|feature table name containing the feature
| rowidfk |foreign key value of the row in the feature table
| type    |Geopaparazzi data type of resource (e.g. BLOB_IMAGE, EXTERNAL_IMAGE, BLOB_PDF, EXTERNAL_PDF)
| resname |file name of resource.  For labeling if resource is "BLOB_*"
| respath |path of resource file
| resblob |if resource is "BLOB_*", contains the resource data as binary
| resthumb|contains a BLOB of a thumbnail of the resource to use as an icon
|====

The ``geopap_resource`` table is used to relate resources like images, PDFs, etc to records in the Spatialite tables.  See <<Feature_Resources, Viewing Feature Attributes>>



