== Vector Editing

In the Map View you can create, view, and edit the geometry and attributes of point, line and polygon features held in a Spatialite database.  You cannot edit Basemap files or Project files.

If you need to create a Spatialite database, press the Import button on the Main View dashboard, and press <<Default databases, Default Database>> (take note of the file name of your new database).

You can use your existing Spatialite databases by attaching them by using the Map View menu item Spatialite data list.


=== Viewing Feature Attributes

After attaching a Spatialite database, turn on the viewing of layers by checking the box next to the layer name.  Back on the Map View, you will see the features (you may need to pan and zoom to them).  To view the attribute values of features, press the Edit Tool button (it looks like a pencil) on the lower right of the Map View.  That will cause the Select button to appear on the lower left.  Press the Select button then press and drag on the Map View to make a box surrounding the features you are interested in.  

If there are any features in the box a Features dialog will appear showing the attribute names and values.  If you've selected more than one feature, you can show their attributes by swiping on the Features dialog.


=== Editing Features

long press on edit button
select layer for editing.  note if the layer is not turned on for viewing, the [pencil] edit button will be black and unavailable to select for editing.  select the green edit button to indicate which layer you want to edit.  the pencil icon will turn red showing the layer is ready for editing.

Back on the Map View press the edit tool button.  Depending on the geometry type of the editing layer various editing buttons will appear.



adding a feature
adding values

Disable editing to leave Map View



